### ISSUE TITLE
Round Corner Edges

### ISSUE THREAD

**Issue by cordhernandez** [JoshuaBayless/Marquee#1]
**Context**
The UI of the app can be enhanced with minor tweaks and updates. Rounding the corner edges of images can really improve aesthetics of an app and make it more pleasing to look at. The goal with this ticket is to round the corner edges of all images in the app.

**Requirements** 
- Add a corner radius to the images in the collection view cells.

Technical Notes
- I think UIKit offers a `corderRadius `property for image views that you might be able to utilize.

**Acceptance Criteria** 
- A screenshot of the corner edge of the images rounded.

**Comment by JoshuaBayless** [comment]
Pull request created for features/RoundedCornerEdges
