### ISSUE TITLE
Shimmer Loading Animation

### ISSUE THREAD

**Issue by cordhernandez** [JoshuaBayless/Marquee#2]
**Context**
The UI of the app can be enhanced with minor tweaks and updates. Adding a shimmer animation for loading images can really improve the UI of an app and make it more engaging. 

**Requirements**
- Add a shimmer loading animation when images are loading.

**Technical** Notes
- There are many third party frameworks that you can use for this, check out the link below.
https://github.com/omerfarukozturk/UIView-Shimmer

**Acceptance Criteria**
- A video or screenshot of the shimmer animation when images are loading.

**Comment by JoshuaBayless** [comment]
Pull request created for features/shimmerAnimations
